### ISSUE TITLE
have problem in yara.CALLBACK_MATCHES

### ISSUE THREAD

**Issue by nanshihui** [VirusTotal/yara-python#77] opened 2018-02-07 01:51 UTC
I installed  yara-python and the version is 3.7.
 However ,i used yara.CALLBACK_MATCHES it showed 
'module' object has no attribute 'CALLBACK_MATCHES'

**Comment by wxsBSD** [comment] 2018-02-07 01:55
Do you have a minimal code snippet which shows this happening? Can you also show the output of ```yara.__version__```?

**Comment by nanshihui** [comment] 2018-02-07 02:03
the output of   yara.__version__   is  "'module' object has no attribute '__version__'".


![image](https://user-images.githubusercontent.com/6913510/35894522-13f7d310-0bee-11e8-874d-51c508e23004.png)

**Comment by wxsBSD** [comment] 2018-02-07 02:09
What's in yara-test.py? The screenshot shows me a stack trace, but not the code which caused it.

**Comment by nanshihui** [comment] 2018-02-07 02:18
![image](https://user-images.githubusercontent.com/6913510/35894944-1b5c4030-0bf0-11e8-9c51-4fcc1ba1d7ac.png)

**Comment by wxsBSD** [comment] 2018-02-07 02:25
Can you `print(yara)` and see where it imported it from?

**Comment by nanshihui** [comment] 2018-02-07 02:33
<module 'yara' from '/usr/lib/python2.7/dist-packages/yara.x86_64-linux-gnu.so'>

**Comment by wxsBSD** [comment] 2018-02-07 02:41
I don't have a clue what's going on here. How, exactly, did you install the YARA python bindings?

**Comment by nanshihui** [comment] 2018-02-07 02:44
I just run ' apt install yara' and 'pip install yara-python'

**Comment by plusvic** [comment] 2018-08-01 08:07
Are you sure you installed it with `pip install yara-python` and not `pip install yara`? There's another package named `yara` (https://pypi.org/project/yara/) which is very out of date.

**Comment by plusvic** [comment] 2018-08-01 08:09
I'm closing this issue as it is likely caused by installing the wrong library. If that's not the case please re-open.

**Closed by plusvic** 2018-08-01 08:09 UTC
