### ISSUE TITLE
Install on MacOS Ventura 13.5

### ISSUE THREAD

**Issue by muckisg** [VirusTotal/yara-python#239] opened 2023-08-16 10:42 UTC
Hi,

i tried to install yara-python via pip but git an error while compilation:

``
yara/libyara/modules/pe/authenticode-parser/authenticode.c:22:10: fatal error: 'openssl/asn1.h' file not found
``

What depencies do i have to correct? Or is it just the correction of a file-/lib-path because i find the missing asn1.h header file e.g. under /opt/homebrew/Cellar/openssl@3/3.1.2/include/openssl/asn1.h?

Thx in advance,
Maurice

**Comment by wxsBSD** [comment] 2023-08-17 18:03
You need to tell the configure script where your OpenSSL headers and libraries are.

```
CFLAGS="-I/opt/homebrew/openssl/include" LDFLAGS="-L/opt/homebrew/openssl/lib" ./configure
```

**Comment by muckisg** [comment] 2023-08-18 05:51
@wxsBSD Thanks for your help but to tell the truth i do not know how to access the configure script because it is part of the pip installation process.  I tried `locate configure | grep yara` to identify a maybe cached configure script but did not find anything.
So, would you help a Apple newbie again? ;-)

Thanks a lot, Maurice

**Comment by wxsBSD** [comment] 2023-08-18 11:31
Sorry, I missed that you were using pip here. I've never done it but you should be able to do:

CFLAGS="-I/opt/homebrew/openssl/include" LDFLAGS="-L/opt/homebrew/openssl/lib" pip instal ...

**Comment by muckisg** [comment] 2023-08-21 08:52
Dear @wxsBSD,

the pip enviroment seems not to work with CFLAGS & LDFLAGS. :-(

In the error message i found the (hardcoded?) search path "/usr/local/opt/openssl/include" so i tried working with a symbolic link but had no success either.

Does anybody has an idea? 

Th@nx a lot,

Maurice

**Comment by plusvic** [comment] 2023-12-29 14:12
Should be fixed in #248

**Closed by plusvic** 2023-12-29 14:12 UTC

**Comment by psifertex** [comment] 2023-12-29 14:35
Is this resolved in pip or does that require a new release? Looks like the last release was in April?

**Comment by lo-chr** [comment] 2023-12-29 16:21
@psifertex: My understanding is, that the version in the pip repository is updated with a new release only.

**Comment by psifertex** [comment] 2023-12-30 21:25
Is there a different issue tracking an updated release on pip that could be linked here then? I ask since one of the plugins in the Binary Ninja community plugin repository depends on this package and installs dependencies via pip so it would be nice to direct people to an issue tracking when it's resolved.

**Comment by 40huo** [comment] 2024-01-30 09:04
```shell
CFLAGS="-I/opt/homebrew/opt/openssl/include" LDFLAGS="-L/opt/homebrew/opt/openssl/lib" pip install yara-python
```
This command works for me.

**Comment by psifertex** [comment] 2024-01-30 17:51
Thanks! I can confirm that works for me too. Good work-around until the release is updated.
